pool:
  name: demoselfhosted

steps:

- task: AzureCLI@2
  displayName: Connect to AML Workspace
  inputs:
    azureSubscription:  'demoMSI'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az ml job list --resource-group aml-private --workspace-name demo-private


- script: |
    echo "Publish ADF pipeline with AML pipeline"
  displayName: 'Publish ADF pipelines'