pool:
  name: demoselfhosted

steps:

- task: AzureCLI@2
  displayName: Connect to AML Workspace
  inputs:
    azureSubscription:  'demoMSI'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az ml folder attach -g $(RESOURCE_GROUP) -w $(AML_WORKSPACE)


- script: |
    echo "Publish ADF pipeline with AML pipeline"
  displayName: 'Publish ADF pipelines'