pool:
  name: "demoselfhosted"

steps:

- task: AzureCLI@2
  displayName: Connect to AML Workspace
  inputs:
    azureSubscription:  'demo'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show