pool:
  name: "demoselfhosted"

steps:

- task: AzureCLI@2
  displayName: Connect to AML Workspace
  inputs:
    azureSubscription:  'aml-workspace-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az ml folder attach -g $(RESOURCE_GROUP) -w $(WORKSPACE_NAME)


- script: |
    echo "Publish ADF pipeline with AML pipeline"
  displayName: 'Publish ADF pipelines'