pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true 

- script: |
    pip install azureml-core==1.40.0
    pip install azureml-pipeline==1.40.0
    pip install azure-cli-core
    az version
    az extension add -n azure-cli-ml
  displayName: 'Installing Dependencies'

- task: AzureCLI@2
  displayName: Connect to AML Workspace
  inputs:
    azureSubscription:  'a9e3b21b-d87f-47a5-8125-99cc1d6b003f'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az ml folder attach -g 'aml-private' -w 'demo-private'


- script: |
    echo "Publish ADF pipeline with AML pipeline"
  displayName: 'Publish ADF pipelines'