pool:
  name: demoselfhosted

steps:
- task: UsePythonVersion@0


- script: |
    pip install azureml-core==1.40.0
    pip install azureml-pipeline==1.40.0
    pip install azure-cli-core
    az version
    az extension add -n azure-cli-ml
  displayName: 'Installing Dependencies'

- task: AzureCLI@2
  displayName: Connect to AML Workspace
  inputs:
    azureSubscription:  'demoMSI'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az ml folder attach -g $(RESOURCE_GROUP) -w $(AML_WORKSPACE)


- script: |
    echo "Publish ADF pipeline with AML pipeline"
  displayName: 'Publish ADF pipelines'